# Generated by Django 5.0.4 on 2024-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_addbooks_options_alter_addbooks_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addbooks",
            name="file_book",
        ),
        migrations.AddField(
            model_name="addbooks",
            name="audio_book",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio_book/",
                verbose_name="Загрузите аудиокнигу",
            ),
        ),
    ]
