# Generated by Django 5.0.4 on 2024-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_addbooks_file_book_addbooks_audio_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите фото'),
        ),
    ]
