# Generated by Django 5.0.4 on 2024-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_addbooks_author_alter_addbooks_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите фото'),
        ),
    ]
